# docker stack deploy -c stack.yml --resolve-image never dockercon-demo

version: '3'

services:

    api-server:
        image: infosiftr/dockercon-demo
        command: dockercon-demo
        ports:
            - 9090:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    echo-server:
        image: infosiftr/dockercon-demo
        command: dockercon-demo
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    worker:
        image: infosiftr/dockercon-demo
        command: dockercon-demo echo-server
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == worker
                    - node.labels.com.infosiftr.dockercon-demo.active == yes
