version: '3'

services:

    api-server:
        image: infosiftr/kubecon-demo
        command: kubecon-demo
        ports:
            - 9090:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

    worker:
        image: infosiftr/kubecon-demo
        command: kubecon-demo api-server
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == worker
                    - node.labels.com.infosiftr.kubecon-demo.active == yes
